services:
  postgres:
    image: postgres:16-alpine
    container_name: querytool_db
    ports:
      - 25432:5432
    volumes:
      - ./:/opt
      - ./app/src/test/resources/dataload/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=querytool
      - POSTGRES_DB=querytool
