services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 25432:5432
    volumes:
      - ./:/opt
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=querytool
      - POSTGRES_DB=querytool
