services:
  postgres:
    image: postgres:16-alpine
    container_name: querytool_db
    ports:
      - 25432:5432
    volumes:
      - ./:/opt
      - ./app/src/test/resources/dataload/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=querytool
      - POSTGRES_DB=querytool
  mariadb:
    image: mariadb:latest
    container_name: mariadb-querytool-db
    environment:
      MYSQL_DATABASE: querytool
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_USER: querytool
      MYSQL_PASSWORD: S3cret
    ports:
      - "23306:3306"
