spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/querytool?currentSchema=querytool
    driver-class-name: org.postgresql.Driver
    username: querytool
    password: S3cret
    platform: postgres